#Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

palette = 'catppuccinMocha-starship-edit'

[palettes.catppuccinMocha-starship-edit]

black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#d7de00'
blue = '#89b4fa'
magenta = '#df0075'
cyan = '#9399b2'
white = '#bfbfbf'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green) ' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = '\[[$symbol$branch]($style)\]'
style = 'bold magenta'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = ' -> '
style = 'bold '#01ded6'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "  -> "
style = 'yellow bold'

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = ' -> '
style = 'bold #dc322f'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = ' -> '
style = 'bold blue'

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = '  '
style = 'bold #0075df'

